### ISSUE TITLE
[Requisitos de estructura] Falta de carptea res_raw

### ISSUE THREAD

**Issue by TupacSierra** [MateoMonastra/Avikoids#2]
Carpeta con assets en crudo (.psd, .ceoil, etc.) que son los editables y que
sirvieron de base para luego crear los assets que carga el juego

**Comment by MateoMonastra** [comment]
> Carpeta con assets en crudo (.psd, .ceoil, etc.) que son los editables y que sirvieron de base para luego crear los assets que carga el juego

No use nada de eso XD
Por eso no hay
